#!/usr/bin/env python3
"""Generate a static brand-accent map from the favicons already used by the site.

Run with a Python environment containing Pillow. The Codex workspace Python
runtime includes it. Failed icons are omitted, leaving the site's neutral theme.
"""

import colorsys
import io
import json
import re
import sys
import urllib.parse
import urllib.request
from concurrent.futures import ThreadPoolExecutor, as_completed
from pathlib import Path

from PIL import Image


ROOT = Path(__file__).resolve().parents[1]
PROFILES = ROOT / "static/company-profiles.js"
OUTPUT = ROOT / "static/company-colors.js"
SOURCE = PROFILES.read_text()
MATCH = re.search(r"window\.FINANCE_COMPANY_PROFILES\s*=\s*(\{.*\});\s*$", SOURCE, re.S)
if not MATCH:
    raise SystemExit("Could not read company profiles")
PROFILES_BY_SYMBOL = json.loads(MATCH.group(1))


def brand_color(raw):
    image = Image.open(io.BytesIO(raw)).convert("RGBA")
    buckets = {}
    for red, green, blue, alpha in image.get_flattened_data():
        if alpha < 128:
            continue
        red = round((red * alpha + 255 * (255 - alpha)) / 255)
        green = round((green * alpha + 255 * (255 - alpha)) / 255)
        blue = round((blue * alpha + 255 * (255 - alpha)) / 255)
        hue, saturation, value = colorsys.rgb_to_hsv(red / 255, green / 255, blue / 255)
        if value > 0.94 and saturation < 0.13:
            continue
        if value < 0.12:
            continue
        key = (red // 24, green // 24, blue // 24)
        score = 1 + saturation * 2.5
        bucket = buckets.setdefault(key, [0, 0, 0, 0])
        bucket[0] += score
        bucket[1] += red * score
        bucket[2] += green * score
        bucket[3] += blue * score
    if not buckets:
        return None
    weight, total_red, total_green, total_blue = max(buckets.values(), key=lambda value: value[0])
    hue, saturation, value = colorsys.rgb_to_hsv(total_red / weight / 255, total_green / weight / 255, total_blue / weight / 255)
    if saturation < 0.17:
        return "#555555"
    red, green, blue = colorsys.hsv_to_rgb(hue, max(saturation, 0.35), min(max(value, 0.35), 0.62))
    return f"#{round(red * 255):02x}{round(green * 255):02x}{round(blue * 255):02x}"


def fetch_color(website):
    url = "https://www.google.com/s2/favicons?" + urllib.parse.urlencode({"sz": 32, "domain_url": website})
    request = urllib.request.Request(url, headers={"User-Agent": "TraderNewsColorBuild/1.0"})
    with urllib.request.urlopen(request, timeout=12) as response:
        return brand_color(response.read(100_000))


websites = {symbol: details.get("website") for symbol, details in PROFILES_BY_SYMBOL.items() if details.get("website")}
existing = {}
if OUTPUT.exists() and "--refresh" not in sys.argv:
    match = re.search(r"window\.FINANCE_COMPANY_COLORS\s*=\s*(\{.*\});\s*$", OUTPUT.read_text(), re.S)
    if match:
        existing = json.loads(match.group(1))
unique_websites = sorted({website for symbol, website in websites.items() if symbol not in existing})
colors_by_website = {}
with ThreadPoolExecutor(max_workers=12) as pool:
    futures = {pool.submit(fetch_color, website): website for website in unique_websites}
    for future in as_completed(futures):
        try:
            color = future.result()
            if color:
                colors_by_website[futures[future]] = color
        except (OSError, ValueError):
            pass

colors = {symbol: existing.get(symbol) or colors_by_website.get(website) for symbol, website in sorted(websites.items())}
colors = {symbol: color for symbol, color in colors.items() if color}
OUTPUT.write_text("/* Generated by scripts/build-company-colors.py from company favicons. */\nwindow.FINANCE_COMPANY_COLORS = " + json.dumps(colors, separators=(",", ":")) + ";\n")
print(f"Saved {len(colors)} colors for {len(websites)} companies to {OUTPUT}")
